openapi: 3.0.3
info:
  title: OGCIO Fastify Scaffolding API
  description: API for OGCIO Fastify Scaffolding
  version: 0.1.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas: {}
paths:
  /health:
    get:
      tags:
        - Health
      description: It checks the current health status of the APIs, pinging all the
        related items
      responses:
        "200":
          description: Default Response
  /api/v1/examples/:
    get:
      operationId: indexExamples
      tags:
        - Examples
      parameters:
        - schema:
            pattern: ^[0-9][0-9]*|undefined$
            default: "0"
            type: string
          in: query
          name: offset
          required: false
          description: Indicates where to start fetching data or how many records to skip,
            defining the initial position within the list
        - schema:
            default: "20"
            pattern: ^([1-9]|100)|undefined$
            type: string
          in: query
          name: limit
          required: false
          description: Indicates the maximum number (100) of items that will be returned
            in a single request
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      description: Example object schema
                      type: object
                      properties:
                        id:
                          format: uuid
                          type: string
                        name:
                          type: string
                      required:
                        - id
                        - name
                  metadata:
                    type: object
                    properties:
                      links:
                        description: Object containing the links to the related endpoints
                        type: object
                        properties:
                          self:
                            type: object
                            properties:
                              href:
                                description: URL pointing to the request itself
                                type: string
                          next:
                            type: object
                            properties:
                              href:
                                description: URL pointing to the next page of results in a paginated response.
                                  If there are no more results, this field may
                                  be omitted
                                type: string
                          prev:
                            type: object
                            properties:
                              href:
                                description: URL pointing to the previous page of results in a paginated
                                  response. If there are no more results, this
                                  field may be omitted
                                type: string
                          first:
                            type: object
                            properties:
                              href:
                                description: URL pointing to the first page of results in a paginated response
                                type: string
                          last:
                            type: object
                            properties:
                              href:
                                description: URL pointing to the first page of results in a paginated response
                                type: string
                          pages:
                            description: It may contain a list of other useful URLs, e.g. one entry for
                              page:'page 1', 'page 2'
                            type: object
                            additionalProperties:
                              type: object
                              properties:
                                href:
                                  type: string
                        required:
                          - self
                          - first
                          - last
                          - pages
                      totalCount:
                        description: Number representing the total number of available items
                        type: number
                required:
                  - data
        4XX:
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    description: Code used to categorize the error
                    type: string
                  detail:
                    description: Description of the error
                    type: string
                  requestId:
                    description: Unique request id. This one will be used to troubleshoot the
                      problems
                    type: string
                  name:
                    description: Name of the error type
                    type: string
                  validation:
                    description: List of the validation errors
                    type: array
                    items:
                      type: object
                      properties:
                        fieldName:
                          type: string
                        message:
                          type: string
                      required:
                        - fieldName
                        - message
                  validationContext:
                    type: string
                  statusCode:
                    type: number
                required:
                  - code
                  - detail
                  - requestId
                  - name
                  - statusCode
        5XX:
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    description: Code used to categorize the error
                    type: string
                  detail:
                    description: Description of the error
                    type: string
                  requestId:
                    description: Unique request id. This one will be used to troubleshoot the
                      problems
                    type: string
                  name:
                    description: Name of the error type
                    type: string
                  validation:
                    description: List of the validation errors
                    type: array
                    items:
                      type: object
                      properties:
                        fieldName:
                          type: string
                        message:
                          type: string
                      required:
                        - fieldName
                        - message
                  validationContext:
                    type: string
                  statusCode:
                    type: number
                required:
                  - code
                  - detail
                  - requestId
                  - name
                  - statusCode
security:
  - bearerAuth: []
